
import Translate from '@/components/Translate';

const IntellectualPropertySection = () => {
  return (
    <section className="border-l-4 border-indigo-500 pl-6 bg-indigo-50 p-6 rounded-r-lg">
      <h2 className="text-2xl font-semibold text-gray-900 mb-4 text-indigo-800">
        <Translate text="legal.termsOfService.ip.title" fallback="Intellectual Property Rights" />
      </h2>
      
      <h3 className="text-xl font-medium text-gray-800 mb-3">Our Property</h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        The SpeechHelp service, including its design, functionality, AI models, and original content, is owned by us and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our written permission.
      </p>
      
      <h3 className="text-xl font-medium text-gray-800 mb-3">Your Content</h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        You retain ownership of the speeches you create using our service. However, you grant us a limited license to process, store, and display your content as necessary to provide our service. You represent that you have the right to create and use such content.
      </p>
      
      <h3 className="text-xl font-medium text-gray-800 mb-3">AI-Generated Content</h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        Content generated by our AI is based on your inputs and our proprietary algorithms. While you may use the generated content, you acknowledge that AI-generated content may not be subject to copyright protection and should be reviewed for accuracy and appropriateness.
      </p>
    </section>
  );
};

export default IntellectualPropertySection;
