// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yotrueuqjxmgcwlbbyps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdHJ1ZXVxanhtZ2N3bGJieXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjIyNDEsImV4cCI6MjA1NjU5ODI0MX0.JNEPQePgfO5ven3C1mUcBvOYezKyjK_zCncPRzuYyXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);